/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package previews;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Person bob = new Person(1, "Sponge Bob");
        System.out.println(bob);
        Course prof = new Course("PROF", 3);
        System.out.println(prof);
    }
}
